from pydantic import Field

from ..mixin import AutoGeneratedIdMixin, CreatedAtMixin

class TranscriptFormatterRecord(AutoGeneratedIdMixin, CreatedAtMixin):
    """
    Pydantic model for a transcript formatter record.
    """
    task_id: str
    """The ID of the task."""
    llm_model_name: str
    """The name of the model used to format the transcript."""
    is_success: bool
    """Whether the formatting is successful."""
    src_fp: str
    """The source file path."""
    # out_fp: str
    # """The output file path."""
    prompt: str
    """The prompt used to format the transcript."""
    # this is the length of the prompt, needn't to be passed in when instantiating the model
    prompt_length: int
    """The length of the prompt."""
    prompt_tokens: int
    """The number of tokens in the prompt."""
    raw_text_length: int
    """The length of the raw text."""
    response: str
    """The response from the model."""
    response_length: int
    """The length of the response."""
    completion_tokens: int
    """The number of tokens in the response."""
    consumed_dollars: float = Field(default=0.0)
    """The consumed dollars for the model to generate the response."""
    consumed_time: float = Field(default=0.0)
    """The consumed time for the model to generate the response."""


__all__ = [
    "TranscriptFormatterRecord",
]
